name: Snyk SCA Scan

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Snyk SCA Scanning
      continue-on-error: true
      run: |
        echo "----------Download Latest Snyk CLI-----------"
        curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1060.0/snyk-linux"
        chmod +x snyk
        ls -lrt
        echo "----------Authenticating Snyk-----------"
        ./snyk auth ${{secrets.Snyk_token}}
        echo "----------Snyk Scanning-----------"
        echo "----------Snyk Monitor------------"
        ./snyk monitor --all-projects --severity-threshold=medium --fail-on=upgradable
