name: PRforsnykwithbash
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  SNykPR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SnykcodeScanning
      run: |
         echo "----------Download Latest Snyk CLI-----------"
         curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1200.0/snyk-linux"
         chmod +x snyk
         ls -lrt
         echo "----------Authenticating Snyk-----------"
         ./snyk auth ${{secrets.Snyk_token}}
         echo "----------Snyk Code Scanning-----------"
         ./snyk code test --report --project-id="7e18c8c3-4040-432c-82c5-8a4ddd9d08e5"
             
             
             
             
             
